[project]
name = "fide-glicko"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "requests>=2.32.5",
    "playwright>=1.48.0",
]
